### ISSUE TITLE
Hi from N26

### ISSUE THREAD

**Issue by luciapayo** [tatocaster/twtest#1]
Hi @tatocaster, this Lucia from N26. 
We reviewed your code challenge and we liked it :)
There is one thing that we would like to request: we consider testing a very important part of the development process and we noticed there are no tests in the code challenge, would it be ok for you to  include some test cases that would cover the most important parts of the app?

**Comment by tatocaster** [comment]
Hi. Quite delayed response :/ 
Because of the tough week, I could not find a time to make tests for the project. Can you check other parts of the challenge and rate without tests?
